name: Deploy iOS Production to App Store

# SECRETS needed:
### SSH_PRIVATE_KEY for Match Repo
### MATCH_PASS
### APP_STORE_CONNECT_API_KEY_BASE64

on:
  workflow_dispatch:
    inputs:
      release_notes:
        required: true
        description: 'Release Notes: User see as Whats New on App Store'
      match_testflight_version:
        type: boolean
        description: 'Match TestFlight newest build. (Optional)'
        required: false

jobs:
  build:
    runs-on: macos-12
    timeout-minutes: 50

    steps:

    - name: Build and Upload to App Store
      run: bundle exec fastlane ios build_upload_appstore --env ios.production release_notes:"${{ github.event.inputs.release_notes }}" build_number_increase:${{ github.event.inputs.match_testflight_version }}
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
