name: Deploy iOS Production to App Store

# SECRETS needed:
### SSH_PRIVATE_KEY for Match Repo
### MATCH_PASS
### APP_STORE_CONNECT_API_KEY_BASE64

on:
  workflow_dispatch:
    inputs:
      release_notes:
        required: true
        description: 'Release Notes: User see as Whats New on App Store'
      match_testflight_version:
        type: boolean
        description: 'Match TestFlight newest build. (Optional)'
        required: false

jobs:
  build:
    runs-on: macos-12
    timeout-minutes: 50

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JAVA
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.0
        cache: 'yarn'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.6'
        bundler-cache: true

    - name: Install Yarn Dependencies
      run: yarn

    - name: Cache Pods
      uses: actions/cache@v2
      id: cocoapodCache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install Pods Dependencies
      run: |
        cd ios
        pod install
      
    - name: Link Resources
      run: yarn react-native link

    - name: Read App Store API Key
      id: app_store_api_key
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'app-store-api-key.json'
        fileDir: './'
        encodedString: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}

    - name: Build and Upload to App Store
      run: bundle exec fastlane ios build_upload_appstore --env ios.production release_notes:"${{ github.event.inputs.release_notes }}" build_number_increase:${{ github.event.inputs.match_testflight_version }}
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iOS ${{ github.sha }}
        path: |
          ${{ github.workspace }}/EasyHotelApp.app.dSYM.zip
